// <auto-generated />
using CoTech.Bi.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoTech.Bi.Migrations
{
    [DbContext(typeof(BiContext))]
    [Migration("20170925065510_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CoTech.Bi.Core.Companies.Models.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activity")
                        .IsRequired();

                    b.Property<string>("Color");

                    b.Property<long?>("CreatorEventId");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long?>("ParentId");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatorEventId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Companies.Models.CompanyToModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CompanyId");

                    b.Property<long>("ModuleId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Company_Has_Modules");
                });

            modelBuilder.Entity("CoTech.Bi.Core.EventSourcing.Models.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyJson")
                        .HasColumnName("Body");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Notifications.Models.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyJson")
                        .HasColumnName("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("SenderId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Notifications.Models.ReceiverEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("NotificationId");

                    b.Property<bool>("Read");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification_Receivers");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Permissions.Models.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CompanyId");

                    b.Property<long?>("CreatorEventId");

                    b.Property<long>("RoleId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatorEventId");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Permissions.Models.RootEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RootUsers");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Users.Models.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatorEventId");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.HasIndex("CreatorEventId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Banks.Models.BankEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired();

                    b.Property<string>("Bank")
                        .IsRequired();

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("RFC")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Budget.Models.BudgetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Amount");

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("CreatorId");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<long>("ExpenseGroupId");

                    b.Property<int>("Month");

                    b.Property<int>("Type");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExpenseGroupId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Clients.Models.ClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("RFC")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("Tradename")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.DinningRooms.Models.DinningRoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("Responsable");

                    b.Property<string>("State");

                    b.Property<int>("Status");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("DinningRooms");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<long>("ExpenseGroupId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Observations");

                    b.Property<float>("Price");

                    b.Property<long?>("ProviderId");

                    b.Property<int>("Quantity");

                    b.Property<long>("RequisitionId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<long?>("CompanyId1");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TypeId");

                    b.Property<long?>("TypeId1");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("TypeId1");

                    b.ToTable("ExpensesGroups");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<long?>("CompanyId1");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompanyId1");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Providers.Models.ProviderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<long>("CompanyId");

                    b.Property<string>("Contact")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("RFC")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("Tradename")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Requisitions.Models.RequisitionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ApplicationDate");

                    b.Property<DateTime>("ApproveDate");

                    b.Property<long?>("ApproveUserId");

                    b.Property<long>("CompanyId");

                    b.Property<DateTime>("ComprobateDate");

                    b.Property<string>("ComprobateFileUrl");

                    b.Property<long?>("ComprobateUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("CreatorId");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("MotiveSurplus");

                    b.Property<string>("PaymentMethod")
                        .IsRequired();

                    b.Property<float>("Refund");

                    b.Property<long>("ResponsableId");

                    b.Property<int>("Status");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ApproveUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ComprobateUserId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Wer.Models.Entities.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Mime");

                    b.Property<string>("Name");

                    b.Property<long>("ReportId");

                    b.Property<string>("Uri");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Wer_File");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Wer.Models.Entities.ReportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CompanyId");

                    b.Property<string>("Financial");

                    b.Property<string>("Observation");

                    b.Property<string>("Operative");

                    b.Property<long>("UserId");

                    b.Property<long>("WeekId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeekId");

                    b.ToTable("Wer_Reports");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Wer.Models.Entities.WeekEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Wer_Weeks");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Companies.Models.CompanyEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.EventSourcing.Models.EventEntity", "CreatorEvent")
                        .WithMany()
                        .HasForeignKey("CreatorEventId");

                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("CoTech.Bi.Core.Companies.Models.CompanyToModule", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany("Modules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.EventSourcing.Models.EventEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.Notifications.Models.NotificationEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.Notifications.Models.ReceiverEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Notifications.Models.NotificationEntity", "Notification")
                        .WithMany("Receivers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.Permissions.Models.PermissionEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.EventSourcing.Models.EventEntity", "CreatorEvent")
                        .WithMany()
                        .HasForeignKey("CreatorEventId");

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.Permissions.Models.RootEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithOne("Root")
                        .HasForeignKey("CoTech.Bi.Core.Permissions.Models.RootEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Core.Users.Models.UserEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.EventSourcing.Models.EventEntity", "CreatorEvent")
                        .WithMany()
                        .HasForeignKey("CreatorEventId");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Banks.Models.BankEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Budget.Models.BudgetEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Modules.Expenses.Models.ExpenseGroupEntity", "ExpenseGroup")
                        .WithMany()
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Clients.Models.ClientEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.DinningRooms.Models.DinningRoomEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Modules.Expenses.Models.ExpenseGroupEntity", "ExpenseGroup")
                        .WithMany()
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Modules.Providers.Models.ProviderEntity", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.HasOne("CoTech.Bi.Modules.Requisitions.Models.RequisitionEntity", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseGroupEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId1");

                    b.HasOne("CoTech.Bi.Modules.Expenses.Models.ExpenseTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId1");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Expenses.Models.ExpenseTypeEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId1");
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Providers.Models.ProviderEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Requisitions.Models.RequisitionEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "ApproveUser")
                        .WithMany()
                        .HasForeignKey("ApproveUserId");

                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "ComprobateUSer")
                        .WithMany()
                        .HasForeignKey("ComprobateUserId");

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Wer.Models.Entities.FileEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Modules.Wer.Models.Entities.ReportEntity", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoTech.Bi.Modules.Wer.Models.Entities.ReportEntity", b =>
                {
                    b.HasOne("CoTech.Bi.Core.Companies.Models.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Core.Users.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoTech.Bi.Modules.Wer.Models.Entities.WeekEntity", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
