using System;

namespace CoTech.Bi.Rx {
  internal delegate void Unsubscriber();
  public class Subscription : IDisposable {
    private Unsubscriber unsubscribe;
    internal Subscription(Unsubscriber unsub){
      this.unsubscribe = unsub;
    }

    // autogenerated
    #region IDisposable Support
    private bool disposedValue = false; // To detect redundant calls

    protected virtual void Dispose(bool disposing) {
      if (!disposedValue) {
        if (disposing) {
          unsubscribe();
        }
        disposedValue = true;
      }
    }

    public void Dispose() {
      Dispose(true);
    }
    #endregion

  }
}